In [26]:
import seaborn as sns
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [27]:
df = pd.read_csv("iris.csv")
df.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [28]:
df.shape

(150, 6)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [30]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [31]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [32]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [33]:
df['Species'] = df['Species'].replace(['Iris-setosa','Iris-versicolor','Iris-virginica'],[0,1,2])

C:\Users\Devanand\AppData\Local\Temp\ipykernel_19096\1123333739.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Species'] = df['Species'].replace(['Iris-setosa','Iris-versicolor','Iris-virginica'],[0,1,2])


In [34]:
df.corr().round(2)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
Id             1.00           0.72         -0.40           0.88          0.90   
SepalLengthCm  0.72           1.00         -0.11           0.87          0.82   
SepalWidthCm  -0.40          -0.11          1.00          -0.42         -0.36   
PetalLengthCm  0.88           0.87         -0.42           1.00          0.96   
PetalWidthCm   0.90           0.82         -0.36           0.96          1.00   
Species        0.94           0.78         -0.42           0.95          0.96   

               Species  
Id                0.94  
SepalLengthCm     0.78  
SepalWidthCm     -0.42  
PetalLengthCm     0.95  
PetalWidthCm      0.96  
Species           1.00

In [35]:
x = df[['PetalWidthCm']]
y = df['Species']

In [36]:
x

PetalWidthCm
0             0.2
1             0.2
2             0.2
3             0.2
4             0.2
..            ...
145           2.3
146           1.9
147           2.0
148           2.3
149           1.8

[150 rows x 1 columns]

In [37]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [39]:
x_train

PetalWidthCm
108           1.8
79            1.0
74            1.3
131           2.0
124           2.1
..            ...
115           2.3
52            1.5
132           2.2
69            1.1
40            0.3

[120 rows x 1 columns]

In [41]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train,y_train)
pred1 = model.predict(x_train)

In [47]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_recall_fscore_support
accuracy_score(y_train,pred1)

0.9666666666666667

In [44]:
pred2 = model.predict(x_test)
accuracy_score(y_test,pred2)

0.9333333333333333

In [46]:
confusion_matrix(y_test,pred2)

array([[ 5,  0,  0],
       [ 0, 16,  0],
       [ 0,  2,  7]], dtype=int64)

In [49]:
precision_recall_fscore_support(y_test,pred2)

(array([1.        , 0.88888889, 1.        ]),
 array([1.        , 1.        , 0.77777778]),
 array([1.        , 0.94117647, 0.875     ]),
 array([ 5, 16,  9], dtype=int64))